/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.11.1/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    `kotlin-dsl`
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `maven-publish`
    //signing

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.plugin.publish)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    //compileOnly("com.android.tools.build:gradle:8.9.2")
    compileOnly(libs.gradle.build.tools)
    api(libs.okhttp3)
    api(libs.okhttp3.logging)

    // Use the Kotlin JUnit 5 integration.
    testImplementation(libs.kotlin.test.junit5)
    testRuntimeOnly(libs.junit.platform.launcher)
}

group = "io.github.tafilovic"
version = "2.0.11"

gradlePlugin {
    website = "https://github.com/tafilovic/central-portal-publisher"
    vcsUrl = "https://github.com/tafilovic/central-portal-publisher.git"
    plugins {
        register("centralPortalPlugin") {
            id = "io.github.tafilovic.central-portal-publisher"
            implementationClass = "io.github.tafilovic.CentralPortalPublisherPlugin"
            displayName = "Central Portal Publishing plugin"
            description =
                "Gradle plugin for use in kotlin and java libraries for publishing to Central Portal"
            tags =
                listOf("central", "portal", "publish", "kotlin", "java", "library", "android")
        }
    }
}